---
# Core
homeassistant: !include includes/homeassistant.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes/
http: !include includes/http.yaml

# Managed via UI
# group: !include groups.yaml # nope
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

# Includes
discovery: !include includes/discovery.yaml
mqtt: !include includes/mqtt.yaml
recorder: !include includes/recorder.yaml
sensor: !include includes/sensor.yaml
weather: !include includes/weather.yaml


