esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  safe_mode: True

# text_sensor:
#   - platform: version
#     name: ${name} Version

sensor:
  - platform: wifi_signal
    name: ${name} Signal
    update_interval: 60s

  # - platform: uptime
  #   name: ${name} Uptime
  #   filters:
  #     - lambda: return x / 3600; 
  #   unit_of_measurement: "h"
  #   accuracy_decimals: 1
  #   update_interval: 60s

  # - platform: adc
  #   pin: VCC
  #   name: ${name} VCC
  #   update_interval: 60s

binary_sensor:
  - platform: status
    name: ${name} Status

# switch:
#   - platform: restart
#     name: ${name} Restart
