substitutions:
  devicename: espcam1
  name: ESP Cam 1

esphome:
  name: ${devicename}
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  safe_mode: True

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: ${name}


text_sensor:
  - platform: version
    name: ${name} Version

sensor:
  - platform: wifi_signal
    name: ${name} Signal
    update_interval: 30s

  - platform: uptime
    name: ${name} Uptime
    filters:
      - lambda: return x / 3600; 
    unit_of_measurement: "h"
    accuracy_decimals: 1
    update_interval: 60s

binary_sensor:
  - platform: status
    name: ${name} Status

switch:
  - platform: restart
    name: ${name} Restart
