substitutions:
  devicename: home_weather_station
  upper_devicename: Home Weather Station

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  safe_mode: True

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: True

text_sensor:
  - platform: version
    name: ${devicename}_esphome_version

sensor:
  - platform: adc
    pin: A0
    name: "Brightness"
    update_interval: 60s

  - platform: bmp280
    address: 0x77
    update_interval: 60s
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"

  - platform: wifi_signal
    name: ${devicename}_wifi_signal
    update_interval: 30s

  - platform: uptime
    name: ${devicename}_uptime

  - platform: adc
    pin: VCC
    name: ${devicename}_vcc_voltage
